# Generated by Django 5.2 on 2025-05-04 22:16

import marketplace.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', marketplace.models.CustomUserManager()),
            ],
        ),
    ]
