# Generated by Django 5.2 on 2025-05-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='api_key',
            field=models.CharField(blank=True, help_text='API ключ для доступа к API маркета', max_length=255),
        ),
        migrations.AddField(
            model_name='market',
            name='api_url',
            field=models.URLField(blank=True, help_text='URL API маркета'),
        ),
        migrations.AddField(
            model_name='market',
            name='search_url_template',
            field=models.CharField(blank=True, help_text='Шаблон URL для поиска товара (используйте {query} для подстановки запроса)', max_length=255),
        ),
    ]
