# Generated by Django 5.2 on 2025-05-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_fakeoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='activation_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
