# Generated by Django 5.2 on 2025-05-05 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_market_api_key_market_api_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='platform_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена товара на нашей платформе', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
